### ISSUE TITLE
Examples of how perform Encryption using this library

### ISSUE THREAD

**Issue by TotalKrill** [neosmart/cryptostream#3]
Would be very nice, since now its an extra step :)

**Comment by mqudsi** [comment]
Is there something that's not covered in the following links?

* https://neosmart.net/blog/2018/transparent-encryption-and-decryption-in-rust-with-cryptostreams/
* https://github.com/neosmart/cryptostream/blob/master/examples/write.rs
* https://github.com/neosmart/cryptostream/blob/master/examples/read.rs
* https://github.com/neosmart/cryptostream/blob/master/README.md
