### ISSUE TITLE
Encryptor/Decryptor: add new functions to convert into inner streams (std::io::Write)

### ISSUE THREAD

**Issue by ghost** [neosmart/cryptostream#4]
Could you add new functions to `Encryptor`/`Decryptor` which convert themselves into their inner streams?

In Rust way, it could be `into_inner(self)`. But I would suggest to use this one:

```rust
pub fn finish(self) -> Result<W>;
```

Inside the functions, they will try to `flush()` the streams.

Thank you,

**Comment by mqudsi** [comment]
Good idea.

**Comment by mqudsi** [comment]
This was ultimately implemented in 6ba6bddf7e3919a7b8317389b4be2633ac3522da and should make it to the next release soon.
